name: 
servings: 4
meal:
category: 
min_period_weeks: 4
ingredients:
  - food:
    quantity: 
  - food:
    quantity: 
  - food:
    quantity: 
  - food:
    quantity: 
  - food:
    quantity: 
  - food:
    quantity: 
  - food:
    quantity: 
  - food:
    quantity: 
  - food:
    quantity: 
  - food:
    quantity: 