name: German Pancakes
servings: 3
ingredients: 
    - 6 eggs
    - 1 cup milk
    - 1 cup flour
    - 1 dash salt
    - 1 teaspoon vanilla extract
    - 5 tablespoons butter
directions:
    - Preheat oven to `425 degrees` F.
    - As oven preheats, put the butter in an un-greased 9x13-in. metal 
        baking dish and place in oven, just until melted.
    - Place the eggs, milk, flour, salt and vanilla in a blender; cover and
        process until smooth. Pour batter into baking dish, over melted butter.
    - Bake, for `22-27 minutes` or until edges are golden brown and puffy.
    - To serve, sprinkle generously with powdered sugar and syrup.

